name = "bigdecimal"
version = "1.3.0"

description = "Arbitrary precision decimal arithmetic for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "bigdecimal" }

[dependencies]
gleam_stdlib = ">= 0.67.1 and < 2.0.0"
bigi = ">= 4.1.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]
